language: java

services:
  - docker

before_install:
  - docker-compose down
  - docker-compose build
  -
jobs:
  include:
    - language: java
      script:
      - docker-compose up -d --force-recreate

after_success:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - aws --version
  - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 673673718278.dkr.ecr.eu-west-1.amazonaws.com
  - docker ps -a
  - docker-compose build
  - docker tag kanban-board_kanban-ui:latest 673673718278.dkr.ecr.eu-west-1.amazonaws.com/kanban_board/kanban-board_kanban-ui:latest
  - docker push 673673718278.dkr.ecr.eu-west-1.amazonaws.com/kanban_board/kanban-board_kanban-ui:latest