language: java

services:
  - docker

before_install:
  - docker-compose down
  - docker-compose build
  -
jobs:
  include:
    - language: java
      script:
      - docker-compose up -d --force-recreate
